godwitVersion = 0.1.0

atlasLocalImage = mongodb/mongodb-atlas-local:8.0
awaitilityVersion = 4.3.0
kotestVersion = 6.2.5
kotlinVersion = 2.4.20
logbackVersion = 1.5.32
mockkVersion = 1.14.9
mongoDriverVersion = 5.7.0
mongoImage = mongo:8.0.17
mongoNewerImage = mongo:8.3
slf4jVersion = 2.0.17
testContainersVersion = 2.0.5
