godwitVersion = 0.1.0

kotlinVersion = 2.4.20

mongoDriverVersion = 5.7.0

slf4jVersion = 2.0.17

kotestVersion = 6.2.5

mockkVersion = 1.14.9

testContainersVersion = 2.0.5

awaitilityVersion = 4.3.0

logbackVersion = 1.5.32

mongoImage = mongo:8.0.17

mongoNewerImage = mongo:8.3

atlasLocalImage = mongodb/mongodb-atlas-local:8.0
