#!/usr/bin/env bash
# Generates docs-snippets/API.md from the godwit-core and godwit-test stub sources in docs-snippets/api-stubs: every
# public file, verbatim, without package and import lines and without "= TODO()" bodies. internals.kt holds
# implementation details and is left out.
set -euo pipefail
cd "$(dirname "$0")/../docs-snippets"
python3 - <<'PY'
import pathlib, re

modules = [
    ("works.resolute:godwit-core", "godwit.core", pathlib.Path("api-stubs/godwit-core/src/main/kotlin/godwit/core")),
    ("works.resolute:godwit-test", "godwit.test", pathlib.Path("api-stubs/godwit-test/src/main/kotlin/godwit/test")),
]
order = ["declaration.kt", "scopes.kt", "ddl.kt", "validation.kt", "Godwit.kt", "GodwitConfig.kt", "reports.kt",
         "exceptions.kt", "testGodwit.kt", "runnerPath.kt", "SessionEscapeDetector.kt"]

out = [
    "# godwit public API",
    "",
    "Generated by `scripts/gen-api.sh` from the compile-checked stubs in `api-stubs/godwit-core/` and",
    "`api-stubs/godwit-test/`. Do not edit by hand: change the stubs, run `./gradlew --offline compileKotlin` in",
    "`docs-snippets/`, then `scripts/gen-api.sh`.",
    "",
    "| Artifact | Package | Runtime dependencies |",
    "|---|---|---|",
    "| `works.resolute:godwit-core` | `godwit.core` | `org.mongodb:mongodb-driver-kotlin-sync:5.7.0` (api), `org.slf4j:slf4j-api:2.0.17` |",
    "| `works.resolute:godwit-test` | `godwit.test` | `godwit-core` (api), `org.testcontainers:testcontainers-mongodb` |",
    "",
    "Bodies are left out; `internal constructor` marks types only godwit creates.",
    "",
]
for artifact, package, root in modules:
    out += [f"## {artifact} (package `{package}`)", ""]
    files = sorted((p for p in root.glob("*.kt") if p.name != "internals.kt"),
                   key=lambda p: order.index(p.name) if p.name in order else len(order))
    for path in files:
        lines = [l for l in path.read_text().splitlines()
                 if not l.startswith("package ") and not l.startswith("import ")]
        text = "\n".join(lines).strip("\n")
        text = re.sub(r"\s*=\s*TODO\(\)", "", text)
        out += [f"### {path.name}", "", "```kotlin", text, "```", ""]

pathlib.Path("API.md").write_text("\n".join(out))
PY
echo "API.md: $(wc -l < API.md | tr -d ' ') lines"
